#!/usr/bin/env python3
"""
GRC-20 Pharmaceutical Knowledge Graph Pipeline Runner

Orchestrates the full pipeline from data sources to final GRC-20 output with provenance.
"""

import sys
import subprocess
from pathlib import Path
import json
import argparse
from datetime import datetime

sys.path.insert(0, str(Path(__file__).parent / "00_schema"))
from pharma_schema import PharmaSchema

# Configuration
BASE_DIR = Path("/mnt/fast_raid/server_projects/Geo/graph_workshop/scripts/production/pipeline")
DATA_DIR = Path("/mnt/fast_raid/server_projects/Geo/graph_workshop/data/grc20_v2")
DAILYMED_XML_DIR = Path("/mnt/fast_raid/server_projects/Geo/graph_workshop/data/dailymed/xml_only")

# Pipeline steps
STEPS = [
    {
        "num": 1,
        "name": "DailyMed",
        "script": "01_dailymed/dailymed_pipeline.py",
        "output": "grc20_with_relations.json",
        "args": ["--skip-download", f"--xml-dir={DAILYMED_XML_DIR}", "--no-validate"]
    },
    {
        "num": 2,
        "name": "RxNorm to GRC-20",
        "script": "02_rxnorm/01_rxnorm_to_grc20.py",
        "output": "rxnorm_entities.json",
        "args": []
    },
    {
        "num": 3,
        "name": "NDC Extraction",
        "script": "03_ndc_bridge/01_extract_ndcs.py",
        "output": "ndc_to_rxcui.json",
        "args": []
    },
    {
        "num": 4,
        "name": "NDC Bridge",
        "script": "03_ndc_bridge/02_ndc_bridge_to_grc20.py",
        "output": "ndc_bridge_entities.json",
        "args": []
    },
    {
        "num": 5,
        "name": "PubChem CID Matching",
        "script": "04_pubchem/01_enrich_by_cid.py",
        "output": "pubchem_cid_mapping.json",
        "args": []
    },
    {
        "num": 6,
        "name": "PubChem Properties",
        "script": "04_pubchem/02_fetch_properties.py",
        "output": "pubchem_properties.json",
        "args": []
    },
    {
        "num": 7,
        "name": "Merge & Enrich",
        "script": "05_triple_converter/01_merge_enrich.py",
        "output": "grc20_merged.json",
        "args": []
    },
    {
        "num": 8,
        "name": "Ensure 100% Provenance",
        "script": "internal",
        "output": "grc20_with_relations.json",
        "args": []
    },
    {
        "num": 9,
        "name": "Validate All",
        "script": "00_schema/validate_all.py",
        "output": None,
        "args": []
    }
]

def run_step(step, limit=None, force=False):
    """Run a single pipeline step."""
    script_path = BASE_DIR / step["script"]
    
    # Build command
    cmd = [sys.executable, str(script_path)]
    
    # Add step-specific arguments
    cmd.extend(step["args"])
    
    # Add limit if supported
    if limit is not None:
        if step["num"] == 1:  # DailyMed
            cmd.extend(["--limit", str(limit)])
    
    # Run
    print(f"Running: {' '.join(cmd)}")
    result = subprocess.run(cmd, cwd=str(BASE_DIR))
    
    return result.returncode == 0

def ensure_provenance_coverage(limit=None):
    """Ensure 100% provenance coverage on the final output."""
    print("\n" + "="*80)
    print("ENSURING 100% PROVENANCE COVERAGE")
    print("="*80 + "\n")
    
    from provenance_manager import ProvenanceManager
    
    pm = ProvenanceManager()
    
    # Load merged entities and relations (JSONL format)
    entities_file = DATA_DIR / "grc20_merged_entities.jsonl"
    relations_file = DATA_DIR / "grc20_merged_relations.jsonl"
    
    if not entities_file.exists():
        print("  ⚠️  No merged entities file found - skipping provenance check")
        return True
    
    print(f"  Loading entities from: {entities_file}")
    print(f"  Loading relations from: {relations_file}")
    
    entities = pm.load_entities_jsonl(str(entities_file))
    relations = pm.load_relations_jsonl(str(relations_file)) if relations_file.exists() else []
    
    # Check coverage
    stats = pm.get_coverage_stats(entities, relations)
    
    print(f"  Total entities: {stats['total_entities']:,}")
    print(f"  Provenance entities: {stats['provenance_entities']}")
    print(f"  Non-provenance entities: {stats['non_provenance_entities']:,}")
    print(f"  With provenance: {stats['with_provenance']:,}")
    print(f"  Without provenance: {stats['without_provenance']:,}")
    print(f"  Current coverage: {stats['coverage']:.1f}%")
    
    # If coverage < 100%, add pipeline_generated provenance
    if stats['coverage'] < 100:
        print(f"\n  Adding provenance to {stats['without_provenance']} entities...")
        
        # Create pipeline_generated provenance
        prov = pm.create_provenance_entity(
            source="pipeline_generated",
            citation="Generated by pharma knowledge graph pipeline v2.0.0",
            date_accessed="2026-03-19",
            provenance_type="GENERATED"
        )
        
        entities.append(prov)
        entities, relations, added = pm.add_provenance_to_entities(
            entities, relations, prov['id']
        )
        
        print(f"  Added {added} provenance relations")
        
        # Save
        pm.save_entities_jsonl(entities, str(entities_file))
        pm.save_relations_jsonl(relations, str(relations_file))
        
        # Verify
        new_stats = pm.get_coverage_stats(entities, relations)
        print(f"  Final coverage: {new_stats['coverage']:.1f}%")
        print("  ✅ Provenance complete!")
    else:
        print("  ✅ Already at 100% coverage")
    
    return True

def clean_outputs():
    """Clean old output files before fresh run."""
    print("\nCleaning old outputs...")
    
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    
    # Only delete backup files, preserve all data files
    for f in DATA_DIR.glob("*.json"):
        if "backup" in f.name.lower():
            f.unlink()
    
    print("  ✅ Cleanup complete (preserved all data files)")

def main():
    parser = argparse.ArgumentParser(description="GRC-20 Pharmaceutical Pipeline Runner")
    parser.add_argument("--limit", type=int, help="Limit number of documents to process")
    parser.add_argument("--force", action="store_true", help="Force rerun of all steps")
    parser.add_argument("--step", type=int, help="Run only specific step")
    parser.add_argument("--clean", action="store_true", help="Clean outputs before running (only for full runs)")
    
    args = parser.parse_args()
    
    print("="*80)
    print("GRC-20 PHARMACEUTICAL KNOWLEDGE GRAPH PIPELINE")
    print("="*80)
    print(f"Started at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    if args.limit:
        print(f"Limit: {args.limit} documents")
    print()
    
    # Clean outputs only for full runs (not when running specific steps)
    if not args.step and args.clean:
        clean_outputs()
    elif not args.step:
        print("[SKIP] Not cleaning outputs (use --clean to clean)")
    else:
        print(f"[STEP {args.step}] Running specific step without cleaning")
    
    # Run steps
    start_step = args.step if args.step else 1
    end_step = args.step if args.step else len(STEPS)
    
    for step in STEPS[start_step-1:end_step]:
        print(f"\n[{step['num']}/{len(STEPS)}] {step['name']}")
        print("-" * 80)
        
        if step['num'] == 8:  # Provenance step
            success = ensure_provenance_coverage(args.limit)
        else:
            success = run_step(step, args.limit, args.force)
        
        if not success:
            print(f"\n❌ Failed at step {step['num']}: {step['name']}")
            sys.exit(1)
        
        print(f"  ✅ Complete")
    
    # Final summary
    output_file = DATA_DIR / "grc20_with_relations.json"
    if output_file.exists():
        size_mb = output_file.stat().st_size / (1024 * 1024)
        print(f"\n" + "="*80)
        print("✅ PIPELINE COMPLETE")
        print("="*80)
        print(f"Output: {output_file}")
        print(f"Size: {size_mb:.2f} MB")
        print(f"Finished at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    else:
        print(f"\n⚠️  Output file not found: {output_file}")

if __name__ == "__main__":
    main()
